### ISSUE TITLE
Sprint #2 Feedback from Team P03 - Error after choosing wrong date for pickup as client

### ISSUE THREAD

**Issue by Paolobd** [rockkytb/SoftEngII-P08-SPG#12]
As a client I think it would be better if only the available days were shown when I want to schedule a pickup. 
In my opinion, it is useless to let me choose dates when pickups are not available and then telling me which are the correct days.
I'd suggest to make it clear earlier which are the available days of the week or to let me choose only those from the calendar

**Comment by rockkytb** [comment]
Fixed, possibility to choose date from wednesday to friday only of the next week
