### ISSUE TITLE
Sprint #2 Feedback from Team P03 - Small flickering issue when confirming order

### ISSUE THREAD

**Issue by Paolobd** [rockkytb/SoftEngII-P08-SPG#13]
I want to point out that I've noticed a small flickering in the page while we were waiting (I think in the cart page) for the correct virtual time to submit the order.
I don't know if this is due to how the page has been constructed or because some numbers/text of the virtual clock take greater space than expected (hence creating this strange effect with the page getting bigger and smaller horizontally periodically)

**Comment by rockkytb** [comment]
Fixed
